"""Worked cases of biologically equivalent resumption after an interruption (fictitious, prostate target).

For each case and each tissue, the dose per session that gives back the planned EQD2 with all the sessions still
possible, and what the tumour-equivalent schedule does to each organ. Model results with the unchanged LQL-Equiv
library (2014 options); the practitioner decides in the clinical context.
Output: docs/lql-resumption-cases.md. Usage: python tools/lql_resumption_cases.py
"""

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from websemantic.lql_interruption import Situation, resume  # noqa: E402

DESC = yaml.safe_load((ROOT / "descriptors" / "lqlequiv" / "descriptor.yaml").read_text(encoding="utf-8"))
ORGANS = ("Rectum", "Small bowel", "Bladder", "Femoral head")
CASES = [
    ("A", "10 × 3 Gy planned, 2 given, 10-day interruption, 5 sessions possible", (3.0, 10, 2, 10, 5)),
    ("B", "as A, 20-day interruption", (3.0, 10, 2, 20, 5)),
    ("C", "as A, only 3 sessions possible", (3.0, 10, 2, 10, 3)),
    ("D", "20 × 3 Gy planned, 5 given, 10-day interruption, 10 sessions possible", (3.0, 20, 5, 10, 10)),
    ("E", "39 × 2 Gy planned, 10 given, 14-day interruption, 20 sessions possible", (2.0, 39, 10, 14, 20)),
]


def fmt(n, d):
    return "out of reach" if d is None else f"{n} × {d:.2f} Gy"


def main():
    lines = ["# Biologically equivalent resumption after an interruption (fictitious cases)", "",
             "Target: prostate. For each tissue, the remaining schedule that gives back its planned EQD2, using all "
             "the sessions still possible. Last columns: organ EQD2 with the tumour-equivalent schedule, as a "
             "difference from its planned EQD2 (negative = less than planned). Model results with the unchanged "
             "LQL-Equiv library (2014 options); simulation for research and education, the practitioner decides "
             "in the clinical context. Generated by tools/lql_resumption_cases.py.", "",
             "| Case | Situation | Without catch-up (tumour) | Tumour | " + " | ".join(ORGANS) + " | "
             + " | ".join(f"{o} with tumour schedule" for o in ORGANS) + " |",
             "|" + "---|" * (4 + 2 * len(ORGANS))]
    for name, text, (dose, planned, done, gap, left) in CASES:
        r = resume(Situation("Prostate", ORGANS, dose, planned, done, gap, left), ROOT, DESC)
        ideal, unc = r["ideal"], r["uncompensated"]
        n = ideal["sessions"]
        cells = [name, text, f"{unc['sessions']} × {unc['dose_per_session']:.1f} Gy: {unc['tumour_deficit_percent']:+.0f} %",
                 fmt(n, ideal["tumour"])] + [fmt(n, ideal["organs"][o]) for o in ORGANS] + [
                 "–" if ideal["organ_excess_with_tumour_schedule_percent"][o] is None
                 else f"{ideal['organ_excess_with_tumour_schedule_percent'][o]:+.1f} %" for o in ORGANS]
        lines.append("| " + " | ".join(cells) + " |")
        print(name, "|", " | ".join(cells[2:]))
    out = ROOT / "docs" / "lql-resumption-cases.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("written", out.relative_to(ROOT))


if __name__ == "__main__":
    main()
