"""Worked cases of biologically equivalent resumption after an interruption (fictitious, prostate target).

Only LQL-Equiv computes. For each case and each tissue separately, the first dose per session (0.01 Gy grid) whose
LQL-Equiv EQD2 reaches the planned EQD2, with all the sessions still possible, and the EQD2 difference of each organ
under the tumour-equivalent schedule. Library defaults, as in the reviewed adapter (legacy_quantisation=False,
reproduce_2014=False, staircase time model). Simulation for research and education; the practitioner decides.
Output: docs/lql-resumption-cases.md. Usage: python tools/lql_resumption_cases.py
"""

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from websemantic.lql_interruption import Situation, resume  # noqa: E402

DESC = yaml.safe_load((ROOT / "descriptors" / "lqlequiv" / "descriptor.yaml").read_text(encoding="utf-8"))
ORGANS = ("Rectum", "Small bowel", "Bladder", "Femoral head")
CASES = [
    ("A", "10 × 3 Gy planned, 2 given, 10-day interruption, 5 sessions possible", (3.0, 10, 2, 10, 5)),
    ("B", "as A, 20-day interruption", (3.0, 10, 2, 20, 5)),
    ("C", "as A, only 3 sessions possible", (3.0, 10, 2, 10, 3)),
    ("D", "20 × 3 Gy planned, 5 given, 10-day interruption, 10 sessions possible", (3.0, 20, 5, 10, 10)),
    ("E", "39 × 2 Gy planned, 10 given, 14-day interruption, 20 sessions possible", (2.0, 39, 10, 14, 20)),
]


def fmt(n, d):
    return "out of reach" if d is None else f"{n} × {d:.2f} Gy"


def main():
    lines = ["# Biologically equivalent resumption after an interruption (fictitious cases)", "",
             "Target: prostate. Only LQL-Equiv computes (pinned library, sha256-checked, library defaults as in the "
             "reviewed adapter: legacy_quantisation=False, reproduce_2014=False, staircase time model). For each "
             "tissue separately, the first dose per session on a 0.01 Gy grid whose EQD2 reaches the planned EQD2, "
             "using all the sessions still possible; these per-tissue schedules do not form one schedule equivalent "
             "for all tissues. Last columns: organ EQD2 under the tumour-equivalent schedule, as a difference from "
             "its planned EQD2 (negative = less than planned). Simulation for research and education; the "
             "practitioner decides in the clinical context. Generated by tools/lql_resumption_cases.py.", "",
             "| Case | Situation | Without catch-up (tumour) | Tumour | " + " | ".join(ORGANS) + " | "
             + " | ".join(f"{o} under tumour schedule" for o in ORGANS) + " |",
             "|" + "---|" * (4 + 2 * len(ORGANS))]
    for name, text, (dose, planned, done, gap, left) in CASES:
        r = resume(Situation("Prostate", ORGANS, dose, planned, done, gap, left), ROOT, DESC)
        best, unc = r["with_all_remaining_sessions"], r["uncompensated"]
        n = best["sessions"]
        diffs = best["organ_difference_with_tumour_schedule_percent"]
        cells = [name, text, f"{unc['sessions']} × {unc['dose_per_session']:.1f} Gy: {unc['tumour_difference_percent']:+.0f} %",
                 fmt(n, best["tumour"])] + [fmt(n, best["organs"][o]) for o in ORGANS] + [
                 "–" if diffs[o] is None else f"{diffs[o]:+.1f} %" for o in ORGANS]
        lines.append("| " + " | ".join(cells) + " |")
        print(name, "|", " | ".join(cells[2:]))
    out = ROOT / "docs" / "lql-resumption-cases.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("written", out.relative_to(ROOT))


if __name__ == "__main__":
    main()
